title: Sentinel Downloader
email: info@zaitra.io
description: >- # this means to ignore newlines until "baseurl:"
  Aplikace na jednoduché stahování volně přístupných dat ze satelitů v programu Copernicus a Landstat.
url: "zaitra.github.io/"

# Build settings
theme: "jekyll-theme-cayman"
